version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "745:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "1337:5000"
    volumes:
      - ./server:/app
      - sqlite-data:/app/instance
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sqlite-data:
    driver: local 